name: Build and Deploy Web App to GitHub Pages
description: This action builds and deploys the web app to GitHub Pages
# on:
#   push:
#     branches:
#       - main  # Trigger the workflow on push to the main branch

runs:
  using: 'docker'
  image: 'node:12'
  steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js with Cache
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
        cache-dependency-path: |
          package-lock.json
          apps/web/package-lock.json

    # Install dependencies
    - name: Install Dependencies
      working-directory: apps/web
      run: npm install

    # Build the app
    - name: Build Web App
      working-directory: apps/web
      run: npm run build:web

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        publish_dir: apps/web/build  # Path to the build output directory
